version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "/var/lib/mysql-cont:/var/lib/mysql:rw"
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
